### ISSUE TITLE
Online workshop/core dev blog idea

### ISSUE THREAD

**Issue by jonathanbossenger** [wptrainingteam/learn-wp-content#4]
Question: Is it possible to use @wordpress/components inside a plugin that has a dashboard UI built in Vue.js?

Context: https://jonathanbossenger.com/2023/02/21/developing-wordpress-blocks-without-react/

**Comment by mateuswetah** [comment]
That is a great question indeed! And a fundamental one if we want developers to start playing around with core JS libraries in the upcoming [Admin Design](https://make.wordpress.org/core/2023/07/12/admin-design/) plans.
